### ISSUE TITLE
3rd test fails

### ISSUE THREAD

**Issue by tunnckoCore** [sindresorhus/registry-url#4]
after 3.0.1 merge, one missing `/` slash at the end

**Comment by kevva** [comment]
Can't reproduce.

**Comment by tunnckoCore** [comment]
in just a moment i ran them and 3rd fails and only. `npm.im/helpers-related` fails, also `npm.im/npm-replated` which is based on this

**Comment by tunnckoCore** [comment]
```
> registry-url@3.0.1 test /home/charlike/dev/registry-url
> mocha



  ✓ should get the npm registry URL globally (40ms)
  ✓ should get the npm registry URL locally 
  ✓ should return local scope registry URL 
  1) should return default npm registry when scope registry not set

  3 passing (107ms)
  1 failing

  1)  should return default npm registry when scope registry not set:
     Uncaught AssertionError: false == true
      at /home/charlike/dev/registry-url/test.js:37:3
      at /home/charlike/dev/registry-url/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:104:5
      at FSReqWrap.oncomplete (fs.js:77:15)

```

**Comment by tunnckoCore** [comment]
yep, because few days I changed the registry and then back it to original. It seems that I set it without last slash `https://registry.npmjs.org`. So normalization is required in this lib.

@sindresorhus @kevva
